baseURL = "http://tatd.at/"
languageCode = "en-us"
title = "dat"
theme = "hugo-xmin"
googleAnalytics = "UA-117499837-1"

pygmentsUseClasses=true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [dat](http://tatd.at) 2018 | [Github](https://github.com/taurandat) | [Linkedin](https://www.linkedin.com/in/trantatdat/)"
